name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
        - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: sudo docker pull pranav910/chatbot-client
    - name: Delete old Docker container
      run: sudo docker rm -f chatbot-client
    - name: Run Docker container
      run: sudo docker run -d -p 8080:8080 --name chatbot-client pranav910/chatbot-client