name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      env:
        DOCKER_USERNAME : ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD : ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build Docker Image
      run: docker build -t pranav910/chatbot-client:latest .

    - name: Push Docker Image to Docker Hub
      run: docker push pranav910/chatbot-client:latest
